//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AbstractField.java
//  @ Date : 29.10.2013
//  @ Author : 
//
//

package ru.netcracker.education;


class AbstractField {
    private FieldCells Field;

    AbstractField() {
        Field = new FieldCells();
    }

    void updateField (Cell move) {
        Field.UpdateField(move);
    }

    FieldCells getField() {
        return Field;
    }
}
