//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AbstractGamer.java
//  @ Date : 29.10.2013
//  @ Author : 
//
//

package ru.netcracker.education;


import java.util.concurrent.*;

public class AbstractGamer implements Callable<Cell> {
    private final FieldCells Field;
    private Cell getNextMove() {
        //here be dragons
        return new Cell(1, 1, true);
    }

    public Cell call() {
        return getNextMove();
    }
    /*
    public void updateFieldCells(Cell move) {
        this.Field.UpdateField(move);
    }
      */
    public AbstractGamer(FieldCells f) {
        this.Field = f;
    }
}
