//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cell.java
//  @ Date : 29.10.2013
//  @ Author : 
//
//

package ru.netcracker.education;


public class Cell {
    private final int Horizontal;
    private final int Vertical;
    private boolean Filled = false;  //in Tic-Tac-Toe matters if it is X or O
    //private boolean FilledWithX = false;
    //private boolean FilledWithO = false;

    /*public boolean CheckValidityOfVCoord(int VerticalCoord) {
        if (VerticalCoord > RangeVerticalLow && VerticalCoord < RangeVerticalHigh) {
            return true;
        }
        return false;
    }
    
    public boolean CheckValidityOfHCoord(int HorizontalCoord) {
        if (HorizontalCoord > RangeHorizontalLow && HorizontalCoord < RangeHorizontalHigh) {
            return true;
        }
        return false;
    }*/

    public Cell(int verticalCoord, int horizontalCoord, boolean filled) {
        this.Horizontal = horizontalCoord;
        this.Vertical = verticalCoord;
    }

    public int getHorizontal() {
        return Horizontal;
    }

    public int getVertical() {
        return Vertical;
    }

    public boolean isFilled() {
        return Filled;
    }

    public void setFilled(boolean filled) {
        this.Filled = filled;
    }
    /*
    public void setFilledX(boolean filled) {
        if (!Filled) {
            FilledWithX = filled;
            Filled = filled;
        }
    }

    public void setFilledO(boolean filled) {
        if (!Filled) {
            FilledWithO = filled;
            Filled = filled;
        }
    }
    */
}
