//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FieldCells.java
//  @ Date : 29.10.2013
//  @ Author : 
//
//
package ru.netcracker.education;



class FieldCells {
    private static final int NUMBER_OF_HORIZONTAL_CELLS = 3;      //Tic-Tac-Toe
    private static final int NUMBER_OF_VERTICAL_CELLS = 3;
    private static final int NUMBER_OF_CELLS = NUMBER_OF_HORIZONTAL_CELLS * NUMBER_OF_VERTICAL_CELLS;
    private Cell[][] Cells;
    FieldCells() {
        Cells = new Cell[NUMBER_OF_HORIZONTAL_CELLS][NUMBER_OF_VERTICAL_CELLS];
        for (int i = 0; i < NUMBER_OF_HORIZONTAL_CELLS; i++) {
            for (int j = 0; j < NUMBER_OF_VERTICAL_CELLS; j++) {
                Cells[i][j] = new Cell(i, j, false);
            }
        }
    }
    
    public Cell[][] getCells() {
        return this.Cells;
    }

    public boolean checkHasWinner(Cell move) {
        return false;
    }
    
    public void UpdateField(Cell move) {
        this.Cells[move.getHorizontal()][move.getVertical()].setFilled(true);
    }
}
