//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Statistics.java
//  @ Date : 29.10.2013
//  @ Author : 
//
//

package ru.netcracker.education;


public class Statistics {
    public Object Players;
    public void Update() {
    
    }
    
    public void CalculateRank() {
    
    }
}
