//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AbstractGamer.java
//  @ Date : 29.10.2013
//  @ Author : 
//
//

package ru.netcracker.education.abstract_classes;


import ru.netcracker.education.Cell;
import ru.netcracker.education.FieldCells;

public abstract class AbstractGamer {
    protected final FieldCells Field;
    public abstract Cell getNextMove();

    public void updateFieldCells(Cell move) {
        this.Field.UpdateField(move);
    }

    public AbstractGamer(FieldCells f) {
        this.Field = f;
    }
}
