//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AbstractField.java
//  @ Date : 29.10.2013
//  @ Author : 
//
//

package ru.netcracker.education.abstract_classes;


import ru.netcracker.education.Cell;
import ru.netcracker.education.FieldCells;

public abstract class AbstractField {
    public FieldCells Field;

    public AbstractField() {
        Field = new FieldCells();
    }

    public abstract void updateField (Cell move);

    public abstract FieldCells getField();
}
