//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AbstractField.java
//  @ Date : 29.10.2013
//  @ Author : 
//
//

package ru.netcracker.education.abstract_classes;


import ru.netcracker.education.Cell;
import ru.netcracker.education.FieldCells;

public abstract class AbstractField {
    private FieldCells Field;

    protected AbstractField() {
        Field = new FieldCells();
    }

    public void updateField (Cell move) {
        Field.UpdateField(move);
    }

    protected FieldCells getField() {
        return Field;
    }
}
